# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cb7a5ff17ce753b34ea871a89b03c8faaac948e265d1120c82bf2aa2266025b034c8c88a0cf7a120558255b4466cb6022c619a401b39d8d1cb69f3224eab1bb3

test:
  secret_key_base: 7ef9fa9e8790042a271ab673f5223984e84c1845eaaefd27ee3942ce0f530376f7ed476e80c003ad9510f75d23877b81ea7893d5fdc849bd7579962808b52c28

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
